import React from "react";
import RiskScore from "./RiskScore";
import SecurityChart from "./SecurityChart";
import StatusBadge from "./StatusBadge";
import ThreatCard from "./ThreatCard";
import UrlTable from "./UrlTable";

export default function AnalysisResult({ analysis }) {
  const confidence = Math.max(0, Math.min(1, Number(analysis.confidence) || 0));
  return <div className="space-y-6">
    <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 shadow-xl shadow-cyan-950/10 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Analysis result · #{analysis.analysis_id}</p><div className="mt-4"><StatusBadge classification={analysis.classification} /></div><h1 className="mt-4 max-w-2xl text-2xl font-semibold tracking-tight text-white">{analysis.summary}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">This result is based on the evidence returned by the text, URL, and header analyzers.</p></div><RiskScore score={analysis.risk_score} classification={analysis.classification} compact /></div><div className="mt-8 grid gap-3 sm:grid-cols-4"><Metric label="Security type" value={formatSecurityType(analysis.security_type)} /><Metric label="Risk score" value={`${Math.round(analysis.risk_score || 0)}/100`} /><Metric label="Confidence" value={`${Math.round(confidence * 100)}%`} /><Metric label="Model version" value={analysis.model_version || "Unavailable"} small /></div><div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs"><span className="text-slate-500">Confidence signal</span><span className="font-semibold text-cyan-300">{Math.round(confidence * 100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800" role="progressbar" aria-label="Analysis confidence" aria-valuenow={Math.round(confidence * 100)} aria-valuemin="0" aria-valuemax="100"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${confidence * 100}%` }} /></div></div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 className="text-sm font-semibold text-white">Component scores</h2><p className="mt-1 text-xs leading-5 text-slate-500">Scores returned by the current backend response.</p><div className="mt-6"><SecurityChart scores={{ text: analysis.text_score, url: analysis.url_score, headers: analysis.header_score }} /></div><p className="mt-5 text-xs leading-5 text-slate-600">Domain and social-engineering signals contribute to the backend risk decision when available, but are not exposed as separate response fields.</p></div></section>

    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Why this result" subtitle="Evidence-backed explanation"><ul className="space-y-3">{analysis.reasons?.length ? analysis.reasons.map((reason, index) => <li key={`${reason}-${index}`} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-300" aria-hidden="true" />{reason}</li>) : <li className="text-sm text-slate-500">No specific suspicious evidence was produced by the available analyzers.</li>}</ul></Panel><Panel title="Recommended actions" subtitle="Defensive next steps"><ul className="space-y-3">{analysis.recommended_actions?.length ? analysis.recommended_actions.map((action, index) => <li key={`${action}-${index}`} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="mt-1 text-emerald-300" aria-hidden="true">✓</span>{action}</li>) : <li className="text-sm text-slate-500">No additional action is recommended from the available evidence.</li>}</ul></Panel></section>

    <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold text-white">Detected threats</h2><p className="mt-1 text-xs text-slate-500">Signals recorded by the analysis pipeline.</p></div><span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-400">{analysis.threats?.length || 0} found</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{analysis.threats?.length ? analysis.threats.map((threat, index) => <ThreatCard key={`${threat.indicator_type}-${threat.value}-${index}`} threat={threat} />) : <p className="text-sm text-slate-500">No threat indicators were recorded.</p>}</div></section>

    <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div><h2 className="text-sm font-semibold text-white">Analyzed URLs</h2><p className="mt-1 text-xs leading-5 text-slate-500">URLs are inspected as strings only. PhishZero never visits them.</p></div><div className="mt-5"><UrlTable urls={analysis.analyzed_urls} /></div></section>
  </div>;
}

function Panel({ title, subtitle, children }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><h2 className="text-sm font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></div>; }
function Metric({ label, value, small = false }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 font-semibold text-white ${small ? "truncate text-sm" : "text-xl"}`} title={small ? value : undefined}>{value}</p></div>; }
function formatSecurityType(value) { return String(value || "UNKNOWN").replaceAll("_", " "); }

