"""add parsed email fields

Revision ID: 4a8634371dbb
Revises: 61577913d01b
Create Date: 2026-08-15 10:18:57.489383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4a8634371dbb'
down_revision: Union[str, None] = '61577913d01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_headers', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('extracted_urls', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('attachment_metadata', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('attachment_metadata')
        batch_op.drop_column('extracted_urls')
        batch_op.drop_column('raw_headers')
        batch_op.drop_column('html_body')

    # ### end Alembic commands ###
