"""initial database schema

Revision ID: 61577913d01b
Revises: 
Create Date: 2026-08-15 10:01:20.221802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '61577913d01b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(email) >= 3', name='ck_users_email_length'),
    sa.CheckConstraint('length(password_hash) >= 20', name='ck_users_password_hash_length'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(recipient) >= 3', name='ck_emails_recipient_length'),
    sa.CheckConstraint('length(sender) >= 3', name='ck_emails_sender_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_emails_user_received_at', ['user_id', 'received_at'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('pending', 'safe', 'spam', 'phishing', 'suspicious')", name='ck_analyses_verdict'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_analyses_confidence_range'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_email_created_at', ['email_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_email_id'), ['email_id'], unique=False)

    op.create_table('analysis_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'analysis_id', name='uq_analysis_feedback_user_analysis')
    )
    with op.batch_alter_table('analysis_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_feedback_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('threat_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_threat_indicators_severity'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'indicator_type', 'value', name='uq_threat_indicators_analysis_type_value')
    )
    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_indicators_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('pending', 'safe', 'malicious', 'suspicious')", name='ck_urls_verdict'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 1)', name='ck_urls_risk_score_range'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'url', name='uq_urls_analysis_url')
    )
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urls_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_domain'), ['domain'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_domain'))
        batch_op.drop_index(batch_op.f('ix_urls_analysis_id'))

    op.drop_table('urls')
    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_indicators_analysis_id'))

    op.drop_table('threat_indicators')
    with op.batch_alter_table('analysis_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_feedback_analysis_id'))

    op.drop_table('analysis_feedback')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_email_id'))
        batch_op.drop_index('ix_analyses_email_created_at')

    op.drop_table('analyses')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index('ix_emails_user_received_at')
        batch_op.drop_index(batch_op.f('ix_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))

    op.drop_table('emails')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

