import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Alert, Button, Spinner } from "../components/common";
import { useAuth } from "../context/AuthContext";

export default function Register() {
  const { register, authError } = useAuth();
  const navigate = useNavigate();
  const [form, setForm] = useState({ displayName: "", email: "", password: "", confirm: "" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function submit(event) { event.preventDefault(); setError(""); if (form.password !== form.confirm) { setError("Passwords do not match."); return; } setLoading(true); try { await register(form.email, form.password, form.displayName); navigate("/dashboard", { replace: true }); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <section className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 shadow-2xl shadow-cyan-950/20 sm:p-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Secure workspace</p><h1 className="mt-3 text-2xl font-semibold text-white">Create your account</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your analysis history stays scoped to your account.</p></div>{error || authError ? <div className="mt-6"><Alert>{error || authError}</Alert></div> : null}<form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium text-slate-200">Display name <span className="text-slate-600">(optional)</span></span><input autoComplete="name" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/10" /></label><label className="block"><span className="mb-2 block text-sm font-medium text-slate-200">Email</span><input type="email" required autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/10" /></label><label className="block"><span className="mb-2 block text-sm font-medium text-slate-200">Password</span><input type="password" required minLength="8" autoComplete="new-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/10" /><span className="mt-2 block text-xs text-slate-600">Use at least 8 characters with a letter and a number.</span></label><label className="block"><span className="mb-2 block text-sm font-medium text-slate-200">Confirm password</span><input type="password" required autoComplete="new-password" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/10" /></label><Button type="submit" className="w-full" disabled={loading}>{loading ? <Spinner label="Creating account" /> : "Create account"}</Button></form><p className="mt-7 text-center text-sm text-slate-500">Already have an account? <Link className="font-semibold text-cyan-300 hover:text-cyan-200" to="/login">Sign in</Link></p></section>;
}
