export const demoEmails = {
  safe: {
    label: "Safe email",
    icon: "🟢",
    description: "Routine library notification with trusted-looking signals.",
    form: {
      sender: "notices@library.example",
      recipient: "demo@example.com",
      subject: "Your reserved book is ready",
      body: "Your reserved book is ready for pickup. Open your usual library app or visit the branch during normal hours. No password or payment is requested in this message.",
      url: "https://library.example/reservations/123",
      headers: "Authentication-Results: mx.example; spf=pass; dkim=pass; dmarc=pass",
    },
    result: {
      classification: "SAFE",
      security_type: "SECURE",
      risk_score: 8,
      confidence: 0.94,
      text_score: 7,
      url_score: 3,
      header_score: 2,
      analyzed_urls: ["https://library.example/reservations/123"],
      model_version: "controlled-demo-v1",
      summary: "This sample has few risk signals and does not ask for sensitive information.",
      reasons: ["The message uses a routine, informational tone.", "No credential or payment request was detected.", "The supplied SPF, DKIM, and DMARC results pass."],
      recommended_actions: ["Verify the notice through your usual library app if needed.", "Do not reuse links or credentials outside their expected context."],
      threats: [],
    },
  },
  spam: {
    label: "Spam email",
    icon: "🟡",
    description: "A promotional message designed to drive a click.",
    form: {
      sender: "offers@weekly-deals.example",
      recipient: "demo@example.com",
      subject: "You won a free gift card — claim today",
      body: "Congratulations! You have been selected for a limited-time reward. Visit the offer page today to claim your gift. Unsubscribe at any time.",
      url: "https://weekly-deals.example/claim",
      headers: "Authentication-Results: mx.example; spf=pass; dkim=unknown; dmarc=unknown",
    },
    result: {
      classification: "LOW_RISK",
      security_type: "LESS_SECURE",
      risk_score: 42,
      confidence: 0.88,
      text_score: 56,
      url_score: 28,
      header_score: 18,
      analyzed_urls: ["https://weekly-deals.example/claim"],
      model_version: "controlled-demo-v1",
      summary: "This sample looks like unsolicited promotional email rather than a targeted credential attack.",
      reasons: ["Reward language encourages a quick click.", "The message is promotional and may be unsolicited.", "Authentication evidence is incomplete."],
      recommended_actions: ["Ignore or unsubscribe using a trusted mail-client control.", "Do not provide personal or payment information to unsolicited offers."],
      threats: [{ indicator_type: "promotional_pressure", value: "limited-time reward", severity: "medium", source: "social_engineering", description: "Promotional pressure was detected." }],
    },
  },
  suspicious: {
    label: "Suspicious email",
    icon: "🟠",
    description: "An account alert with an unexpected verification path.",
    form: {
      sender: "support@account-security.example",
      recipient: "demo@example.com",
      subject: "Unusual sign-in attempt detected",
      body: "We noticed a sign-in from a new device. Review the activity at the link below and contact support if it was not you. We will never ask for your password by email.",
      url: "https://account-security.example/login-check",
      headers: "Authentication-Results: mx.example; spf=pass; dkim=unknown; dmarc=pass",
    },
    result: {
      classification: "SUSPICIOUS",
      security_type: "SUSPICIOUS",
      risk_score: 67,
      confidence: 0.86,
      text_score: 63,
      url_score: 65,
      header_score: 38,
      analyzed_urls: ["https://account-security.example/login-check"],
      model_version: "controlled-demo-v1",
      summary: "This sample combines an account alert with a link that should be independently verified.",
      reasons: ["An unexpected sign-in alert creates pressure to review activity.", "The message directs the recipient to an account-related URL.", "DKIM is not explicitly confirmed in the supplied headers."],
      recommended_actions: ["Open the service through a known bookmark instead of the email link.", "Check account activity directly and report the message if unexpected."],
      threats: [{ indicator_type: "account_alert", value: "unusual sign-in attempt", severity: "medium", source: "social_engineering", description: "An account-alert pattern was detected." }],
    },
  },
};

